import Head from "next/head";
import css from "../styles/Home.module.css";
import { useTranslation } from "../hooks/useTranslation";
import Container from "@/components/Container/Container";
import Table from "@/components/Table/Table";
import Overlay from "@/components/Overlay/Overlay";
import ClientsList from "@/components/Clients/Clients";
import path from "../components/PhotoGallery/imagesMainPage.json";
import ScrollTopBtn from "@/components/ScrollTopBtn/ScrollTopBtn";
import { useEffect, useState } from "react";
import Thread from "@/components/Thread/Thread";
import FaqSection from "@/components/FAQ/FaqSection";

interface HomeProps {
  imagePaths: string[];
}

const Home: React.FC<HomeProps> = ({ imagePaths }) => {
  const { t } = useTranslation();

  const [isMobile, setIsMobile] = useState(false);
  const [opacity, setOpacity] = useState(1);

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= 768);
    };

    handleResize();
    window.addEventListener("resize", handleResize);

    return () => window.removeEventListener("resize", handleResize);
  }, []);

  useEffect(() => {
    const handleScroll = () => {
      const scrollY = window.scrollY;
      const newOpacity = Math.max(1 - scrollY / 300, 0);
      setOpacity(newOpacity);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <div className={css.hero}>
            <Container>
              <h1 className={css.description} style={{ opacity }}>
                {t.homeP.description1}
                <span className={css.description2}>{t.homeP.description2}</span>
              </h1>
            </Container>
          </div>
          <Container>
            <div className={css.about}>
              <div className={css.about__counter}>
                <ul className={css.about__counter_list}>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>14</span>
                      {t.homeP.years}
                    </p>
                  </li>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>382</span>
                      {t.homeP.kids}
                    </p>
                  </li>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>679</span>
                      {t.homeP.adult}
                    </p>
                  </li>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>737</span>
                      {t.homeP.corporate}
                    </p>
                  </li>
                </ul>
              </div>
              <h2 className={css.about_title}>{t.homeP.aboutTitle}</h2>
              <p className={css.about_text}>{t.homeP.aboutText}</p>
            </div>
          </Container>
          <Thread imagePaths={imagePaths} double />
          <Overlay />
          <Container>
            <Table />
          </Container>
          {isMobile && <Overlay />}
          <Container>
            <div className={css.video}>
              <iframe
                src="https://www.youtube.com/embed/tUHAoshTRQ0?si=zuLF6Ij4gPv7G3bo"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerPolicy="strict-origin-when-cross-origin"
                allowFullScreen
              ></iframe>
              <iframe
                src="https://www.youtube.com/embed/CY4_zTEm_sk?si=aN5_bPGc3OMPlLku"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerPolicy="strict-origin-when-cross-origin"
                allowFullScreen
              ></iframe>
            </div>
          </Container>
          <FaqSection />
          <ClientsList />
          <ScrollTopBtn />
        </main>
      </div>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  return {
    props: {
      imagePaths: path,
    },
  };
}
