import Head from "next/head";
import css from "../styles/Home.module.css";
import { useTranslation } from "../hooks/useTranslation";
import Container from "@/components/Container/Container";
import Table from "@/components/Table/Table";
import Overlay from "@/components/Overlay/Overlay";
import ClientsList from "@/components/Clients/Clients";
import Image from "next/image";
import imagePaths from "../components/PhotoGallery/imagesMainPage.json";
import ScrollTopBtn from "@/components/ScrollTopBtn/ScrollTopBtn";

interface ImageFile {
  id: string;
  src: string;
  alt: string;
  width: number;
  height: number;
}

const link = "https://mafiadream.com.ua/wp-content/images/";

export async function getStaticProps() {
  const imagesFiles: ImageFile[] = imagePaths.images.map((path, index) => ({
    id: `${index + 1}`, // Динамічне id
    src: `${link}${path}`, // Повний шлях до зображення
    alt: `Image ${index + 1}`, // Динамічний alt
    width: 600,
    height: 400,
  }));

  return {
    props: {
      imagesFiles,
    },
  };
}
interface ImageGalleryProps {
  imagesFiles: ImageFile[];
}

const Home: React.FC<ImageGalleryProps> = ({ imagesFiles }) => {
  const { t } = useTranslation();
  const doubledImages = [...imagesFiles, ...imagesFiles];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <div className={css.hero}>
            <Container>
              <p className={css.mafia}>
                MAFIA
                <span className={css.dream}>DREAM CLUB</span>
              </p>
              <h1 className={css.description}>
                {t.homeP.description1}
                <span className={css.enter}></span>
                {t.homeP.description2}
              </h1>
            </Container>
          </div>
          <Container>
            <div className={css.about}>
              <div className={css.about__counter}>
                <ul className={css.about__counter_list}>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>14</span>
                      {t.homeP.years}
                    </p>
                  </li>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>382</span>
                      {t.homeP.kids}
                    </p>
                  </li>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>679</span>
                      {t.homeP.adult}
                    </p>
                  </li>
                  <li className={css.item}>
                    <p className={css.counter_text}>
                      <span className={css.sum}>737</span>
                      {t.homeP.corporate}
                    </p>
                  </li>
                </ul>
              </div>
              <h2 className={css.about_title}>{t.homeP.aboutTitle}</h2>
              <p className={css.about_text}>{t.homeP.aboutText}</p>
            </div>
          </Container>
          <div className={css.gallery}>
            <ul className={css.gallery_list}>
              {doubledImages.map((img, index) => (
                <li className={css.gallery_item} key={`${img.id}-${index}`}>
                  <Image
                    src={img.src}
                    alt={img.alt}
                    width={img.width}
                    height={img.height}
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    className={css.imageThumbnail}
                  />
                </li>
              ))}
            </ul>
          </div>
          <Overlay />
          <Container>
            <Table />
          </Container>
          <ClientsList />
          <ScrollTopBtn/>
        </main>
      </div>
    </>
  );
};

export default Home;
